feeds:
  - https://www.reuters.com/finance/markets/rss
  - https://www.bankofengland.co.uk/news/news.xml
  - https://www.ons.gov.uk/news/rss
  - https://www.vanguardinvestor.co.uk/rss/insights.xml
  - https://monevator.com/feed/
